### PR TITLE
Fix Issue 9

### PR DESCRIPTION
**Pull request by kennystrawnmusic**
To make the code editor less dependent on screen resolution, my changes to the code editor being pull-requested against perform calculations using screen.availWidth and screen.availHeight to create the window in proportion to said bounds. Hopefully they will be accepted upstream... Screenshot of what the changes do attached below.
screenshot 2013-07-17 at 11 18 51

### CODE REVIEW

**Comment by sowbug** [comment]
We might also want to add an id (http://developer.chrome.com/apps/app.window.html#method-create) so that if this isn't what people want -- think 30-inch monitor on Chromebox -- they can adjust it and it'll remember the previous position. Thoughts?

**Comment by dinhvh** [comment]
I also think the window should be singleton'ed.

**Comment by kennystrawnmusic** [comment]
@sowbug Testing the above on my Chromebook in question (since the only way to get Git on a Chromebook is with the developer switch on) right now... Let's see what happens.

**Comment by kennystrawnmusic** [comment]
Okay, confirmed: Merely adding an ID suddenly allows the bounds to be remembered even when the window is destroyed. As for singletoning it as @dinhviethoa mentioned: "singleton: true" according to the app.window API is the default behavior, so no issues there.

**Pull request merged**
